package com.arena.hidcompatibilitytester.ui.screen.keyboard

import com.arena.hidcompatibilitytester.settings.PortraitKeyboardSettings
import com.arena.hidcompatibilitytester.settings.SettingsSectionStyle
import com.arena.hidcompatibilitytester.settings.SettingsMediaRowGroup
import com.arena.hidcompatibilitytester.settings.SettingsHapticIntensity
import com.arena.hidcompatibilitytester.settings.SettingsKeyHeight
import com.arena.hidcompatibilitytester.settings.SettingsKeyFontSize
import com.arena.hidcompatibilitytester.settings.SettingsMediaKeySize
import com.arena.hidcompatibilitytester.settings.SettingsKeysTabSection
import com.arena.hidcompatibilitytester.settings.SettingsNavTabSection
import com.arena.hidcompatibilitytester.settings.SettingsMediaTabSection
import com.arena.hidcompatibilitytester.settings.SettingsOptionalRow

typealias KeyboardSettings = PortraitKeyboardSettings
typealias SectionStyle = SettingsSectionStyle
typealias MediaRowGroup = SettingsMediaRowGroup
typealias HapticIntensity = SettingsHapticIntensity
typealias KeyHeight = SettingsKeyHeight
typealias KeyFontSize = SettingsKeyFontSize
typealias MediaKeySize = SettingsMediaKeySize
typealias KeysTabSection = SettingsKeysTabSection
typealias NavTabSection = SettingsNavTabSection
typealias MediaTabSection = SettingsMediaTabSection
typealias KeyboardOptionalRow = SettingsOptionalRow